#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

puts "Loading render-caching gem"
exec "#{irb} -r irb/completion -r #{File.dirname(__FILE__) + '/../lib/render_caching.rb'} --simple-prompt"
